# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a6118d970233156cefb00baa899def3d0aad3b747e5bbd0b36c1111b2e05ddfeae7114747701fae9cb1ba5b54ec95059c9dfdaa029202379d5f4e772af35d62

test:
  secret_key_base: e659815143979b49ae2519b69a8b8b0893870a128c38e41dda4aa0c0975a94ec2b706d0ec32bae99469e468b8f10e70b4f846eb888a6e405da0b3aac7a60d221

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
